# Generated by Django 6.0.3 on 2026-04-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='offline_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
