# Generated by Django 6.0.3 on 2026-04-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_offline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='location_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
    ]
