# Generated by Django 6.0.3 on 2026-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('bleeding', 'Bleeding'), ('burn', 'Burn'), ('fracture', 'Fracture'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('priority_level', models.CharField(default='high', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
