# Generated by Django 6.0.3 on 2026-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyguide',
            name='priority_level',
        ),
        migrations.AlterField(
            model_name='emergencyguide',
            name='case_type',
            field=models.CharField(choices=[('bleeding', 'Bleeding'), ('burn', 'Burn'), ('fracture', 'Fracture'), ('other', 'Other')], max_length=20, unique=True),
        ),
    ]
